spring:
  application:
    name: nt-ribbon-rest
  profiles:
    active: default
      
#Spring eureka配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Logging 配置
logging:
  file: /data/logs/sloth/${spring.application.name}/${spring.application.name}.log
  level:
    com.fd.sloth.ribbon: INFO

server:
  context-path: /
  port: 19001
