spring:
  application:
    name: nt-ribbon-rest
  profiles:
    active: default
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
      
#Spring eureka配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Logging 配置
logging:
  file: /data/logs/sloth/${spring.application.name}/${spring.application.name}.log
  level:
    com.fd.sloth.ribbon: INFO

server:
  context-path: /
  port: 19001
